LigaDeportiva/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # urls para la aplicacion asistencia
    url(r'^', include('apps.users.urls', namespace="users_app")),
    # url(r'^', include('apps.prueba.urls', namespace="prueba_app")),
    # urls para la aplicacion users
    url(r'^', include('apps.torneo.urls', namespace="torneo_app")),
    url(r'^', include('apps.equipo.urls', namespace="equipo_app")),
    url(r'^', include('apps.incidencias.urls', namespace="incidencias_app")),
    url(r'^', include('apps.jugador.urls', namespace="jugador_app")),
    # url(r'^', include('apps.libro.urls', namespace="libro_app")),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, }),
    ]

apps/equipo/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        r'^facultad/$',
        views.RegistrarFacultad.as_view(),
        name='registrar-facultad'
    ),
    url(
        r'^facultad/listar/$',
        views.ListFacultad.as_view(),
        name='listar-facultad'
    ),
    url(
        r'^facultad/detalle/(?P<pk>\d+)$',
        views.detalleFacultad.as_view(),
        name='detalle-facultad'
    ),
    url(
        r'^facultad/modificar/(?P<pk>\d+)$',
        views.ModificarFacultad.as_view(),
        name='modificar-facultad'
    ),
    url(
        r'^facultad/eliminar/(?P<pk>\d+)$',
        views.EliminarFacultad.as_view(),
        name='eliminar-facultad',
    ),
    url(
        r'^equipo/modificar/$',
        views.ActualizarEquipo.as_view(),
        name='modificar-equipo',
    ),
    url(
        r'^equipo/junta/secreatario$',
        views.ModificarSecretario.as_view(),
        name='modificar-secretario',
    ),
    url(
        r'^equipo/junta/tesorero$',
        views.ModificarTesorero.as_view(),
        name='modificar-tesorero',
    ),
    url(
        r'^comando/modificar/$',
        views.ActualizarComandoTecnico.as_view(),
        name='modificar-comando',
    ),
    url(
        r'^juntadirectiva/modificar/$',
        views.ActualizarJuntaDirectiva.as_view(),
        name='modificar-junta',
    ),
    url(
        r'^Pago/(?P<pk>\d+)$',
        views.RegistrarPago.as_view(),
        name='registrar-Pago'
    ),
    url(
        r'^Pago/listar/$',
        views.ListPago.as_view(),
        name='listar-Pago'
    ),
    url(
        r'^Pago/detalle/(?P<pk>\d+)$',
        views.detallePago.as_view(),
        name='detalle-Pago'
    ),
    url(
        r'^Pago/modificar/(?P<pk>\d+)$',
        views.ModificarPago.as_view(),
        name='modificar-Pago'
    ),
    url(
        r'^Pago/eliminar/(?P<pk>\d+)$',
        views.EliminarPago.as_view(),
        name='eliminar-Pago',
    ),
    url(
        r'^equipo/comando/tecnico$',
        views.ModificarTecnico.as_view(),
        name='modificar-tecnico',
    ),
    url(
        r'^equipo/comando/medico$',
        views.ModificarMedico.as_view(),
        name='modificar-medico',
    ),
    url(
        r'^equipo/comando/preparador$',
        views.ModificarPreparador.as_view(),
        name='modificar-preparador',
    ),
    url(
        r'^equipo/comando/delegado$',
        views.ModificarDelegado.as_view(),
        name='modificar-delegado',
    ),

    ##############################urls para frotend###############
    url(
        r'^equipo/listar/$',
        views.ListarEquipo.as_view(),
        name='listar-equipos'
    ),
]

apps/jugador/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
         r'^consulta/jugadores$',
         views.ListJugadores.as_view(),
         name='consulta-jugadores'
    ),
    # habilitar jugadores para un partido
    url(
    	r'^jugador/seleccion$',
    	views.SeleccionJugadores.as_view(),
    	name='seleccion-jugadores'
    ),
    # lista de jugadores habilitados
    url(
        r'^jugador/habilitados$',
        views.JugadoresHabilitados.as_view(),
        name='consulta-habilitados'
    ),
    url(
    	r'^consulta/equipos$',
    	views.ListaEquiposToreno.as_view(),
    	name='consulta-equipos'
    ),
    url(
    	r'^consulta/jugadores-equipo/(?P<pk>\d+)$',
    	views.ListaJugadoresEquipo.as_view(),
    	name='consulta-jugadores'
    ),
    url(
    	r'^consulta/amonestacion/(?P<pk>\d+)$',
    	views.JugadorAmonestacion.as_view(),
    	name='consulta-amonestacion'
    ),
    url(
    	r'^consulta/goleadores$',
    	views.ListaGoleadores.as_view(),
    	name='consulta-goleadores'
    ),
    # ----- URL GOLES ------
    url(
        r'^goleadores-equipos/(?P<pk>\d+)$',
        views.ListaEquipoPartido.as_view(),
        name='equipo-partido'
    ),
    url(
        r'^goleadores-add/(?P<pk>\d+)/(?P<pa>\d+)/$',
        views.RegistrarGoleadores.as_view(),
        name='registrar-goleadores'
    ),
    url(
        r'^goleadores/modificar/(?P<pk>\d+)$',
        views.ModificarGoleadores.as_view(),
        name='modificar-goleadores'
    ),
    url(
        r'^goleadores/eliminar/(?P<pk>\d+)$',
        views.EliminarGoleadores.as_view(),
        name='eliminar-goleadores',
    ),
    url(
        r'^goleadores/listar-todo$',
        views.ListaGoleador.as_view(),
        name='listar-gool',
    ),
    ### jugador
    url(
        r'^jugador/$',
        views.RegistrarJugador.as_view(),
        name='registrar-jugador'
    ),
    url(
        r'^jugador/listar/$',
        views.ListJugador.as_view(),
        name='listar-jugador'
    ),
    url(
        r'^jugador/detalle/(?P<pk>\d+)$',
        views.detalleJugador.as_view(),
        name='detalle-jugador'
    ),
    url(
        r'^jugador/modificar/(?P<pk>\d+)$',
        views.ModificarJugador.as_view(),
        name='modificar-jugador'
    ),
    url(
        r'^jugador/eliminar/(?P<pk>\d+)$',
        views.EliminarJugador.as_view(),
        name='eliminar-jugador'
    ),
    url(
        r'^jugador/amonestados/lista$',
        views.JugadoresAmonestados.as_view(),
        name='jugador-amonestados',
    ),
    url(
        r'^jugador/amonestados/duda/(?P<pk>\d+)$',
        views.JugadorDeudas.as_view(),
        name='jugador-deuda',
    ),
    url(
        r'^amonestacion/listaequipo/',
        views.ListaEquiposAmonestar.as_view(),
        name='lista-equipo-amonestacion'
    ),
    url(
        r'^amonestacion/lista$',
        views.ListarAmonestacion.as_view(),
        name='listar-amonestacion',
    ),
    url(
        r'^amonestacion/registrar/(?P<pk>\d+)$',
        views.RegistrarAmonestacion.as_view(),
        name='registrar-amonestacion'
    ),
    url(
        r'^amonestacion/modificar/lista/(?P<pk>\d+)$',
        views.ModificarAmonestacion.as_view(),
        name='modificar-amonestacion',
    ),
    url(
        r'^amonestacion/elimnar/lista/(?P<pk>\d+)$',
        views.EliminarAmonestacion.as_view(),
        name='eliminar-amonestacion',
    ),
]

apps/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        r'^$',
        views.HomeView.as_view(),
        name='home'
    ),
    url(
        r'^partidos/$',
        views.PartidoView.as_view(),
        name='partidos'
    ),
    url(
        r'^clasificacion/$',
        views.ClasificacionView.as_view(),
        name='clasificacion'
    ),
    url(
        r'^panel/$',
        views.InicioView.as_view(),
        name='inicio'
    ),
    url(
        r'^login/$',
        views.LogIn.as_view(),
        name='login'
    ),
    url(
        r'^usuario/salir/$',
        'apps.users.views.LogOut',
        name='logout'
    ),
    url(
        r'^add-admin/$',
        views.AgregarAdministrador.as_view(),
        name='agregar-administrador'
    ),
    url(
        r'^add-admin-equipo/$',
        views.AgregarAdmiEquipo.as_view(),
        name='administrador-equipo'
    ),
    url(
        r'^paneljunta/$',
        views.PanelJuntaDirectiva.as_view(),
        name='panel_juntadirectiva'
    )
    ,
    url(
        r'^ListAdmin/$',
        views.ListAdminEquipo.as_view(),
        name='Lista-Admin-Equipo'
    )
]

apps/users/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

class UserManager(BaseUserManager, models.Manager):

    def _create_user(self, username, email, password, is_staff, is_superuser, **extra_fields):

        email = self.normalize_email(email)
        if not email:
            raise ValueError("el email es obligatorio")

        user = self.model(
            username=username,
            email=email,
            is_active=True,
            is_staff=is_staff,
            is_superuser=is_superuser,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email, password=None, **extra_fields):
        return self._create_user(username, email, password, False, False, **extra_fields)

    def create_superuser(self, username, email, password=None, **extra_fields):
        return self._create_user(username, email, password, True, True, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):

    GENDER_CHOICES = (
        ('M', 'MASCULINO'),
        ('F', 'FEMENINO'),
    )
    TYPE_CHOICES = (
        ('1', 'Administrador'),
        ('2', 'Junta Directiva'),
    )
    username = models.CharField('dni', max_length=8, unique=True)
    email = models.EmailField('correo electronico')
    first_name = models.CharField('nombres', max_length=50)
    last_name = models.CharField('apellidos', max_length=50)
    avatar = models.ImageField(upload_to='users', blank=True, null=True)
    address = models.CharField('direccion', max_length=50)
    phone = models.CharField('telefono', max_length=50)
    gender = models.CharField('sexo', max_length=1, choices=GENDER_CHOICES)
    date_birth = models.DateField('fecha de nacimiento', blank=True, null=True)
    type_user = models.CharField('tipo de usuario', max_length=2, choices=TYPE_CHOICES, null=True, blank=True)

    objects = UserManager()

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return "%s %s" % (self.username, self.first_name)

    def __unicode__(self):
        return "%s %s" % (self.username, self.last_name)

templates/panel/paneljuntadirectiva/base_panel.html
{% extends "base.html" %}

{% load  staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/materialize.css' %}">
    <link rel="stylesheet" href="{% static 'css/stylepanel.css' %}">
    <link href='http://fonts.googleapis.com/css?family=Ubuntu:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

{% endblock css %}
{% block sidenav %}
    <header>
        <nav class="top-nav cyan">
            <div class="container">
              <div class="nav-wrapper">
                <a href="#"></a>
                <a class="page-title">
                    {% block titulo_nav %}{% endblock titulo_nav %}</a>
              </div>
            </div>
        </nav>
        <div class="container">
            <a href="#" data-activates="nav-mobile" class="button-collapse top-nav full">
              <i class="mdi-navigation-menu"></i>
            </a>
        </div>
        <ul id="nav-mobile" class="side-nav fixed">
            <li class="logo cyan">
              <div id="logo-container">
                <div class="row">
                  <div class="col col-profile s4">
                    {% if not user.avatar %}
                      <img src="{% static 'img/neunapp.png' %}" class="circle responsive-img valign">
                    {% else %}
                        <img src="{{ user.avatar.url }}" alt="{{ user.get_full_name }}" class="circle responsive-img valign">
                    {% endif %}
                  </div>
                  <div class="col col-profile s8">
                    <ul id="profile-dropdown" class="dropdown-content">
                      <li><a href="/"> inicio</a>
                      </li>
                      <li class="divider"></li>
                      <li><a href="{% url 'users_app:logout' %}">Salir</a>
                      </li>
                    </ul>
                    <a class="waves-effect waves-light btn-flat white-text dropdown-button profile-btn" data-activates="profile-dropdown">{{ user.first_name }}<i class="mdi-navigation-arrow-drop-down right-profile"></i></a>
                    <p class="user-roal">{{ user.get_type_user_display }}</p>
                  </div>
                </div>
              </div>
            </li>

            {% block funciones %}{% endblock funciones %}

        </ul>
    </header>
    <main>
        {% block mensaje %}{% endblock mensaje %}
        {% block contenido_panel %}
        {% endblock contenido_panel %}

    </main>

{% endblock sidenav %}

{% block js %}
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{% static 'js/materialize.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/init.js' %}"></script>
{% endblock js %}

templates/panel/paneljuntadirectiva/footer.html
<footer class="page-footer">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Footer Content</h5>
                <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
              </div>
              <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
                  <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © 2014 Copyright Text
            <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
          </div>
</footer>

templates/panel/paneljuntadirectiva/panel.html
{% extends "panel/base_panel.html" %}

{% block title %}panel{% endblock title %}

  {% block titulo_nav %} Junta Directiva Equipos{% endblock titulo_nav %}

    {% block funciones %}
    <li class="no-padding">
        <ul class="collapsible collapsible-accordion">
            <li class="bold"><a class="collapsible-header  waves-effect waves-ripple">Junta Directiva</a>
                <div class="collapsible-body">
                    <ul>
                        <li><a href="{% url 'equipo_app:modificar-secretario' %}">Secretario</a></li>
                        <li><a href="{% url 'equipo_app:modificar-tesorero' %}">Tesorero</a></li>
                    </ul>
                </div>
            </li>

            <li class="bold"><a class="collapsible-header  waves-effect waves-ripple">Comando Tecnico</a>
                <div class="collapsible-body">
                    <ul>
                        <li><a href="{% url 'equipo_app:modificar-tecnico' %}">D. Tecnico</a></li>
                        <li><a href="{% url 'equipo_app:modificar-preparador' %}">Preparador</a></li>
                        <li><a href="{% url 'equipo_app:modificar-medico' %}">Medico</a></li>
                        <li><a href="{% url 'equipo_app:modificar-delegado' %}">Delegado</a></li>
                    </ul>
                </div>
            </li>

            <li class="bold"><a class="collapsible-header  waves-effect waves-ripple">Jugadores</a>
                <div class="collapsible-body">
                    <ul>
                        <li><a href="{% url 'jugador_app:registrar-jugador' %}">Registrar</a></li>
                        <li><a href="{% url 'jugador_app:listar-jugador' %}">Plantel</a></li>
                        <li><a href="{% url 'jugador_app:seleccion-jugadores' %}">Convocar</a></li>
                        <li><a href="{% url 'jugador_app:consulta-habilitados' %}">Jugadores Convocados</a></li>
                    </ul>
                </div>
            </li>

            <li class="bold"><a class="collapsible-header  waves-effect waves-ripple">Equipo</a>
                <div class="collapsible-body">
                    <ul>
                        <li><a href="{% url 'equipo_app:modificar-equipo' %}">Resgistrar Equipo</a></li>
                    </ul>

                    <ul>
                        <li><a href="{% url 'jugador_app:consulta-jugadores' %}">Goleadores</a></li>
                        <li><a href="{% url 'jugador_app:jugador-amonestados' %}">Amonestados</a></li>
                    </ul>
                </div>
            </li>

        </ul>
        <div class="col s1">
                <a class="btn-large disabled" href="http://127.0.0.1:8000/"><i class="fa fa-chevron-left left"></i>Home</a>
    </div>
    </li>
    {% endblock funciones %}