LigaDeportiva/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # urls para la aplicacion asistencia
    url(r'^', include('apps.users.urls', namespace="users_app")),
    # url(r'^', include('apps.prueba.urls', namespace="prueba_app")),
    # urls para la aplicacion users
    url(r'^', include('apps.torneo.urls', namespace="torneo_app")),
    url(r'^', include('apps.equipo.urls', namespace="equipo_app")),
    url(r'^', include('apps.incidencias.urls', namespace="incidencias_app")),
    url(r'^', include('apps.jugador.urls', namespace="jugador_app")),
    # url(r'^', include('apps.libro.urls', namespace="libro_app")),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, }),
    ]

apps/torneo/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import url
from . import views


urlpatterns = [
    ####### URL QUE LE CORRESPONDE A LA TABLA CAMPO DEPORTIVO ################
    url(
        r'^torneo/registrar-campo-deportivo/$',
        views.RegistrarCampoD.as_view(),
        name='registrar_CampoD'
    ),
    url(
        r'^torneo/listar-campo-deportivo/$',
        views.ListarCampoD.as_view(),
        name='listar_CampoD'
    ),
    url(
        r'^campoD/detalle/(?P<pk>\d+)$',
        views.detalleCampoD.as_view(),
        name='detalle_CampoD'
    ),
    url(
        r'^campoD/modificar/(?P<pk>\d+)$',
        views.ModificarCampoD.as_view(),
        name='modificar_CampoD'
    ),
    url(
        r'^campoD/eliminar/(?P<pk>\d+)$',
        views.EliminarCampoD.as_view(),
        name='eliminar_CampoD',
    ),
    ####### URL QUE LE CORRESPONDE A LA TABLA PERSONA ################
    url(
        r'^persona/registrar$',
        views.RegistrarPersona.as_view(),
        name='registrar_persona'
    ),
    url(
        r'^persona/listar$',
        views.ListPersona.as_view(),
        name='listar-persona'
    ),
    url(
        r'^persona/detalle/(?P<pk>\d+)$',
        views.DetallePersona.as_view(),
        name='detalle_persona'
    ),
    url(
        r'^persona/modificar/(?P<pk>\d+)$',
        views.ModificarPersona.as_view(),
        name='modificar_persona'
    ),
    url(
        r'^persona/eliminar/(?P<pk>\d+)$',
        views.EliminarPersona.as_view(),
        name='eliminar_persona'
    ),
    ####### URL QUE LE CORRESPONDE A LA TABLA TORNEO ################
    url(
        r'^torneo/registrar$',
        views.RegistrarTorneo.as_view(),
        name='registrar_torneo'
    ),
    url(
        r'^torneo/listar$',
        views.ListTorneo.as_view(),
        name='listar_torneo'
    ),
    url(
        r'^torneo/detalle/(?P<pk>\d+)$',
        views.DetalleTorneo.as_view(),
        name='detalle_torneo'
    ),
    url(
        r'^torneo/modificar/(?P<pk>\d+)$',
        views.ModificarTorneo.as_view(),
        name='modificar_torneo'
    ),
    url(
        r'^torneo/eliminar/(?P<pk>\d+)$',
        views.EliminarTorneo.as_view(),
        name='eliminar_torneo'
    ),
    ####### URL QUE LE CORRESPONDE A LA TABLA ARBITRO ################
    url(
        r'^torneo/registrar_arbitro/$',
        views.RegistrarArbitro.as_view(),
        name='registrar_arbitro'
    ),
    url(
        r'^torneo/listar_arbitro/$',
        views.ListarArbitro.as_view(),
        name='listar_arbitro'
    ),
    url(
        r'^torneo/detalle_arbitro/(?P<pk>\d+)$',
        views.detalleArbitro.as_view(),
        name='detalle_arbitro'
    ),
    url(
        r'^torneo/modificar_arbitro/(?P<pk>\d+)$',
        views.ModificarArbitro.as_view(),
        name='modificar_arbitro'
    ),
    url(
        r'^campoD/eliminar_arbitro/(?P<pk>\d+)$',
        views.EliminarArbitro.as_view(),
        name='eliminar_arbitro',
    ),
    ####### URL QUE LE CORRESPONDE A LA PrecioPago ################
    url(
        r'^torneo/registrar_PrecioPago/$',
        views.RegistrarPrecioPago.as_view(),
        name='registrar_PrecioPago'
    ),
    url(
        r'^torneo/listar_PrecioPago/$',
        views.ListarPrecioPago.as_view(),
        name='listar_PrecioPago'
    ),
    url(
        r'^torneo/detalle_PrecioPago/(?P<pk>\d+)$',
        views.detallePrecioPago.as_view(),
        name='detalle_PrecioPago'
    ),
    url(
        r'^torneo/modificar_PrecioPago/(?P<pk>\d+)$',
        views.ModificarPrecioPago.as_view(),
        name='modificar_PrecioPago'
    ),
    url(
        r'^campoD/eliminar_PrecioPago/(?P<pk>\d+)$',
        views.EliminarPrecioPago.as_view(),
        name='eliminar_PrecioPago',
    ),
    url(
        r'^torneo/culiminar$',
        views.CulminarView.as_view(),
        name='culminar-torneo',
    ),
]

apps/torneo/forms.py
# -*- encoding: utf-8 -*-
from django import forms

from models import CampoDeportivo, Persona, Arbitro, Fixture, PrecioPago, Torneo


class CampoDForm(forms.ModelForm):

    class Meta:
        model = CampoDeportivo
        fields = ("__all__")

    def clean_nombre(self):
        nom = self.cleaned_data['nombre']
        num_palabras = len(nom)
        if num_palabras < 5:
            raise forms.ValidationError("nombre muy corto")
        return nom

    def clean_prop(self):
        prop = self.cleaned_data['propietario']
        num_palabras = len(prop)
        if num_palabras < 5:
            raise forms.ValidationError("Nombre de Propietario muy corto")
        return prop


class PersonaForm(forms.ModelForm):
    class Meta:
        model = Persona
        fields = (
            'dni',
            'nombres',
            'apellidos',
            'email',
            'direccion',
            'sexo',
            'telefono',
            'fecha_nacimineto',
            'foto',
        )
        widgets = {
            'sexo': forms.Select(attrs={'class': 'validate'}),
            'fecha_nacimineto': forms.DateInput(attrs={'class': 'datepicker'}),
            'avatar': forms.ClearableFileInput(attrs={'class': 'validate'}),
        }

    def clean_dni(self):
        documento = self.cleaned_data['dni']
        persona = Persona.objects.filter(dni=documento)
        if persona.count() > 0:
            raise forms.ValidationError("el dni ya existe")
        return documento


class TorneoForm(forms.ModelForm):
    class Meta:
        model = Torneo
        fields = ("__all__")
        widgets = {
            'fecha_inicio': forms.DateInput(attrs={'class': 'datepicker'}),
            'fecha_fin': forms.DateInput(attrs={'class': 'datepicker'}),
        }
    def clean_nombre(self):
        nom = self.cleaned_data['nombre']
        torneo = Torneo.objects.all().order_by('fecha_inicio')
        print '=============='
        print 'torneo'
        if torneo.count() > 0:
            if torneo[torneo.count()-1].culminado == False:
                raise forms.ValidationError("ya existe un torneo inciado")
        return nom

class PrecioPagoForm(forms.ModelForm):
    class Meta:
        model = PrecioPago
        fields = ("__all__")

class ArbitroForm(PersonaForm):
    experiencia = forms.IntegerField()

    class Meta(PersonaForm.Meta):
        # campos q se van a mostar en el formulario pre_matricula
        fields = (
            'dni',
            'nombres',
            'apellidos',
            'email',
            'direccion',
            'sexo',
            'telefono',
            'fecha_nacimineto',
            'foto',
        )

class CulminarForm(forms.Form):
    nombre = forms.CharField()

    def clean_nombre(self):
        name = self.cleaned_data['nombre']
        print name
        torneo = Torneo.objects.get(culminado=False)
        print torneo.nombre
        if not torneo.nombre == name:
            raise forms.ValidationError("Ingrese Nombre Correcto")
        return name

apps/torneo/views.py
# -*- encoding: utf-8 -*-
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView, UpdateView, DeleteView, DetailView, ListView
from django.views.generic.edit import FormView, FormMixin
from django.core.urlresolvers import reverse_lazy, reverse


from .forms import CampoDForm, PersonaForm, TorneoForm, ArbitroForm, PrecioPagoForm, CulminarForm
from .models import CampoDeportivo, Persona, Torneo, Arbitro, Fixture, PrecioPago
from .functions import Resultados_Equipos, CulminarTorneo
from apps.users.models import User


from django.http import HttpResponseRedirect
from django.utils import timezone


# Create your views here.
#Mantenimientos del campo deportivo
class ListarCampoD(ListView):
    context_object_name = 'campos'
    queryset = CampoDeportivo.objects.all()
    template_name = 'torneo/campodeportivo/listar.html'


class RegistrarCampoD(CreateView):
    form_class = CampoDForm
    template_name = "torneo/campodeportivo/agregar.html"
    success_url = reverse_lazy('torneo_app:listar_CampoD')


class detalleCampoD(DetailView):
    template_name = 'torneo/campodeportivo/detalle.html'
    model = CampoDeportivo


class ModificarCampoD(UpdateView):
    #le especificamos la tabla de BD
    model = CampoDeportivo
    # le pasamos el template donde se pintaran los datos recureados
    template_name = 'torneo/campodeportivo/modificar.html'
    success_url = reverse_lazy('torneo_app:listar_CampoD')
    #le pasamos el formulario en el que recibiremos los datos a modificar
    form_class = CampoDForm


#utilizamos DeleteView que se encarga de recibir y elimnar los dato de la BD
class EliminarCampoD(DeleteView):
    #pasamos el template donde se mostraara los datos que vamos a eliminar
    template_name = 'torneo/campodeportivo/eliminar.html'
    #pasamos el modelo del cual se eliminara elregistro
    model = CampoDeportivo
    #donde ira cuando se complete la accion
    success_url = reverse_lazy('torneo_app:listar_CampoD')


class ListPersona(ListView):
    context_object_name = 'personas'
    queryset = Persona.objects.all()
    template_name = 'torneo/persona/listar.html'


class RegistrarPersona(CreateView):
    form_class = PersonaForm
    template_name = "torneo/persona/agregar.html"
    success_url = reverse_lazy('torneo_app:listar-persona')


class DetallePersona(DetailView):
    # pasamos hatml donde se pintara el detalle del objeto
    template_name = 'torneo/persona/detalle.html'
    #pasamos el modelo o tabla del objeto
    model = Persona


class ModificarPersona(UpdateView):
    #le especificamos la tabla de BD
    model = Persona
    # le pasamos el template donde se pintaran los datos recureados
    template_name = 'torneo/persona/modificar.html'
    success_url = reverse_lazy('torneo_app:listar-persona')
    #le pasamos el formulario en el que recibiremos los datos a modificar
    form_class = PersonaForm


class EliminarPersona(DeleteView):
    #pasamos el template donde se mostraara los datos que vamos a eliminar
    template_name = 'torneo/persona/eliminar.html'
    #pasamos el modelo del cual se eliminara elregistro
    model = Persona
    #donde ira cuando se complete la accion
    success_url = reverse_lazy('torneo_app:listar-persona')


class ListTorneo(ListView):
    template_name = 'torneo/torneo/listar.html'
    context_object_name = 'torneos'
    model = Torneo


class RegistrarTorneo(CreateView):
    form_class = TorneoForm
    template_name = "torneo/torneo/agregar.html"
    success_url = reverse_lazy('torneo_app:listar_torneo')


class DetalleTorneo(DetailView):
    template_name = 'torneo/torneo/detalle.html'
    #pasamos el modelo o tabla del objeto
    model = Torneo


class ModificarTorneo(UpdateView):
    model = Torneo
    template_name = 'torneo/torneo/modificar.html'
    success_url = reverse_lazy('torneo_app:listar_torneo')
    #le pasamos el formulario en el que recibiremos los datos a modificar
    form_class = TorneoForm


class EliminarTorneo(DeleteView):
    template_name = 'torneo/torneo/eliminar.html'
    model = Torneo
    success_url = reverse_lazy('torneo_app:listar_torneo')


#Mantenimientos del arbitro
class ListarArbitro(ListView):
    context_object_name = 'campos'
    queryset = Arbitro.objects.all()
    template_name = 'torneo/arbitro/listar.html'


#clase para registrar un equipo utilizando createview
class RegistrarArbitro(CreateView):
    form_class = ArbitroForm
    template_name = "torneo/arbitro/agregar.html"
    success_url = reverse_lazy('torneo_app:listar_arbitro')

    def form_valid(self, form):
        # recojemos los datos de perona
        persona = Persona(
            dni=form.cleaned_data['dni'],
            nombres=form.cleaned_data['nombres'],
            apellidos=form.cleaned_data['apellidos'],
            email=form.cleaned_data['email'],
            direccion=form.cleaned_data['direccion'],
            sexo=form.cleaned_data['sexo'],
            telefono=form.cleaned_data['telefono'],
            foto=form.cleaned_data['foto'],
        )
        persona.save()
        arbitro = Arbitro(
            persona=persona,
            experiencia=form.cleaned_data['experiencia']
        )
        arbitro.save()
        return super(RegistrarArbitro, self).form_valid(form)


#clase para ver los datos en detalle de un solo equipo
# utilizaremos un DetaiView que se encarga de recibir el id de equipo
class detalleArbitro(DetailView):
    # pasamos hatml donde se pintara el detalle del objeto
    template_name = 'torneo/arbitro/detalle.html'
    #pasamos el modelo o tabla del objeto
    model = Arbitro


class ModificarArbitro(UpdateView):
    #le especificamos la tabla de BD
    model = Arbitro
    # le pasamos el template donde se pintaran los datos recureados
    template_name = 'torneo/arbitro/modificar.html'
    success_url = reverse_lazy('torneo_app:listar_arbitro')
    #le pasamos el formulario en el que recibiremos los datos a modificar
    form_class = ArbitroForm


class EliminarArbitro(DeleteView):
    #pasamos el template donde se mostraara los datos que vamos a eliminar
    template_name = 'torneo/arbitro/eliminar.html'
    #pasamos el modelo del cual se eliminara elregistro
    model = Arbitro
    #donde ira cuando se complete la accion
    success_url = reverse_lazy('torneo_app:listar_arbitro')
    ########################################PrecioPago

    #Mantenimientos del PrecioPago
class ListarPrecioPago(ListView):
    context_object_name = 'campos'
    queryset = PrecioPago.objects.all()
    template_name = 'torneo/PrecioPago/listar.html'


#clase para registrar un PrecioPago utilizando createview
class RegistrarPrecioPago(CreateView):
    form_class = PrecioPagoForm
    template_name = "torneo/PrecioPago/agregar.html"
    success_url = reverse_lazy('torneo_app:listar_PrecioPago')


#clase para ver los datos en detalle de un solo equipo
# utilizaremos un DetaiView que se encarga de recibir el id de equipo
class detallePrecioPago(DetailView):
    # pasamos hatml donde se pintara el detalle del objeto
    template_name = 'torneo/PrecioPago/detalle.html'
    #pasamos el modelo o tabla del objeto
    model = PrecioPago


class ModificarPrecioPago(UpdateView):
    #le especificamos la tabla de BD
    model = PrecioPago
    # le pasamos el template donde se pintaran los datos recureados
    template_name = 'torneo/PrecioPago/modificar.html'
    success_url = reverse_lazy('torneo_app:listar_PrecioPago')
    #le pasamos el formulario en el que recibiremos los datos a modificar
    form_class = PrecioPagoForm


class EliminarPrecioPago(DeleteView):
    #pasamos el template donde se mostraara los datos que vamos a eliminar
    template_name = 'torneo/PrecioPago/eliminar.html'
    #pasamos el modelo del cual se eliminara elregistro
    model = PrecioPago
    #donde ira cuando se complete la accion
    success_url = reverse_lazy('torneo_app:listar_PrecioPago')


#clase que culmira un tonero para crea un nuevo torneo
class CulminarView(FormView):
    template_name = 'torneo/torneo/culminar.html'
    form_class = CulminarForm
    success_url = reverse_lazy('torneo_app:listar_torneo')

    def get_context_data(self, **kwargs):
        context = super(CulminarView, self).get_context_data(**kwargs)
        context['torneo'] = Torneo.objects.get(culminado=False)
        context['resultados'] = Resultados_Equipos()
        return context

    def form_valid(self, form):
        print '=====Entro al Form Valid===='
        nombre = form.cleaned_data['nombre']
        torneo = Torneo.objects.get(culminado=False)
        torneo.culminado = True
        torneo.save()
        CulminarTorneo()
        return super(CulminarView, self).form_valid(form)

templates/torneo/arbitro/agregar.html
{% extends "panel/panel.html" %}

{% block contenido_panel %}
{% load staticfiles %}

            <div class="row">
              {% if form.errors %}
                  <div class="card-panel red lighten-1">
                      <span class="white-text"> {{ form.errors }} </span>
                  </div>
                  <div class="divider"></div>
              {% endif %}
              <div class="card">
                <div class="col s10 m6 ">
                    <form class="col s12" method="POST" enctype="multipart/form-data">{% csrf_token %}
                      <div class="row">

                        {{form.as_p}}

                        <div class="row">
                                <div class="input-field col s12">
                                      <button class="btn cyan waves-effect waves-light center" type="submit" name="action">Guardar Arbitro
                                        <i class="mdi-content-send right"></i>
                                      </button>
                                </div>
                        </div>

                      </div>

                    </form>
                </div>
              </div>
        </div>
{% endblock contenido_panel %}

templates/torneo/arbitro/detalle.html
{% extends "panel/panel.html" %}

{% block contenido_panel %}
{% load staticfiles %}

<div class="container panel-container">
        <div class="row">
            <div class="col s5">
                <a class="waves-effect waves-light btn btn-back" href="{% url 'torneo_app:listar_arbitro' %}"><i class="fa fa-chevron-left left"></i>Regresar</a>
            </div>
            <div class="col s7">
                <h5>Arbitro: {{ object.pk }} detalle</h5>
            </div>
        </div>

        <div class="divider"></div>
        
        <div class="row">
            <div class="col s12 m6 l6">
                <div class="card-panel">
                    <div class="row">
                        <ul class="collection">
                           <li class="collection-item">
                                <span class="title">Persona:</span>
                                <p>{{ object.persona }}</p>
                            </li>
                            <li class="collection-item">
                                <span class="title">Experiencia:</span>
                                <p>{{ object.experiencia}}</p>
                            </li>
                        </ul> <!-- fin de collection -->
                    </div>

                </div><!-- fin de card-panel -->

            </div>
        </div><!-- fin de row -->
        
    </div><!-- fin de panel-container -->

{% endblock contenido_panel %}

templates/torneo/arbitro/eliminar.html
{% extends "panel/panel.html" %}

{% block contenido_panel %}
{% load staticfiles %}

    <div class="container panel-container">
        <div class="row">
            <div class="col s12">
                <h5>Eliminando: {{ object.persona }}</h5>
            </div>
        </div>

        <div class="divider"></div>
        
        <div class="row">
            <div class="col s12 m6 offset-m3">
                <div class="card-panel grey lighten-5 z-depth-1">
                    <div class="row valign-wrapper">
                        <form action="{% url 'torneo_app:eliminar_arbitro' object.pk %}" method="POST">{% csrf_token %}
                            <div class="col s12">
                                <h6 class="center-align">¿Desea eliminar al arbitro "{{ object.persona }}"?</h6>
                            </div>
                            <div class="col s12 center">
                                <button class="waves-effect waves-light btn btn-panel red" type="submit" name="action">si</button>
                                <a href="{% url 'torneo_app:listar_arbitro' %}" class="waves-effect waves-light btn panel-btn white black-text">no</a>
                            </div>
                        </form>                        
                    </div>
                </div><!-- fin de card-panel -->

            </div>
        </div><!-- fin de row -->
        
    </div><!-- fin de panel-container -->

{% endblock contenido_panel %}

templates/torneo/arbitro/listar.html
{% extends "panel/panel.html" %}

{% block contenido_panel %}
{% load staticfiles %}

    <div class="container panel-container">
      <div class="row">
          <div class="col s6 m4">
          <p><a class="waves-effect waves-light btn" href="{% url 'torneo_app:registrar_arbitro' %}"><i class="fa fa-plus left"></i>agregar Arbitro</a></p>
        </div>
      </div>
      <div class="divider"></div>
      <div class="row">
        <table class="hoverable centered bordered responsive-table">
        <thead>
          <tr>
              <th>Persona</th>
              <th>Experiencia</th>
              
          </tr>
        </thead>
        <tbody>

          {% for campo in  campos %}
            <tr>
              <td>{{ campo.persona }}</td>
              <td>{{ campo.experiencia }}</td>
              <td>
               <a href="{% url 'torneo_app:detalle_arbitro' campo.pk %}" class="waves-effect waves-light btn panel-btn green"><i class="fa fa-eye"></i></a>
               <a href="{% url 'torneo_app:modificar_arbitro' campo.pk %}" class="waves-effect waves-light btn panel-btn yellow"><i class="fa fa-edit"></i></a>
               <a href="{% url 'torneo_app:eliminar_arbitro' campo.pk %}" class="waves-effect waves-light btn panel-btn red"><i class="fa fa-trash-o"></i></a>
              </td>
            </tr>            
          {% endfor %}

        </tbody>
      </table>
      </div>
    </div>
{% endblock contenido_panel %}

templates/torneo/arbitro/modificar.html
{% extends "panel/panel.html" %}

{% block contenido_panel %}
{% load staticfiles %}

    <div class="container panel-container">
        <div class="row">
            <div class="col s5">
                <a class="waves-effect waves-light btn btn-back" href="{% url 'torneo_app:listar_arbitro' %}"><i class="fa fa-chevron-left left"></i>Regresar</a>
            </div>
            <div class="col s7">
                <h5>Modificando: {{ object.pk }}</h5>    
            </div>
        </div>


        <div class="divider"></div>
        {% if form.errors %}
            <div class="card-panel red lighten-1">
                <span class="white-text"> {{ form.errors }} </span>
            </div>
            <div class="divider"></div>
        {% endif %}
        <div class="row">
            <div class="col s12 m6 l6">
                <div class="card-panel">
                    <div class="row">
                        <form class="col s12" action="{% url 'torneo_app:modificar_arbitro' object.pk %}" method="POST">{% csrf_token %}
                            
                            <div class="row">
                                <div class="input-field col s12">
                                    {{ form.persona }}
                                    {{ form.persona.label_tag }}
                                </div>
                            </div>
                            
                            <div class="row">
                                <div class="input-field col s12">
                                    {{ form.experiencia}}
                                    {{ form.experiencia.label_tag }}
                                </div>
                            </div>

                            <div class="row">
                                <div class="input-field col s12">
                                      <button class="btn cyan waves-effect waves-light right" type="submit" name="action">actualizar
                                        <i class="mdi-content-send right"></i>
                                      </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div><!-- fin de card-panel -->

            </div>
        </div><!-- fin de row -->
        
    </div><!-- fin de panel-container -->
{% endblock contenido_panel %}