LigaDeportiva/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # urls para la aplicacion asistencia
    url(r'^', include('apps.users.urls', namespace="users_app")),
    # url(r'^', include('apps.prueba.urls', namespace="prueba_app")),
    # urls para la aplicacion users
    url(r'^', include('apps.torneo.urls', namespace="torneo_app")),
    url(r'^', include('apps.equipo.urls', namespace="equipo_app")),
    url(r'^', include('apps.incidencias.urls', namespace="incidencias_app")),
    url(r'^', include('apps.jugador.urls', namespace="jugador_app")),
    # url(r'^', include('apps.libro.urls', namespace="libro_app")),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, }),
    ]

apps/equipo/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        r'^facultad/$',
        views.RegistrarFacultad.as_view(),
        name='registrar-facultad'
    ),
    url(
        r'^facultad/listar/$',
        views.ListFacultad.as_view(),
        name='listar-facultad'
    ),
    url(
        r'^facultad/detalle/(?P<pk>\d+)$',
        views.detalleFacultad.as_view(),
        name='detalle-facultad'
    ),
    url(
        r'^facultad/modificar/(?P<pk>\d+)$',
        views.ModificarFacultad.as_view(),
        name='modificar-facultad'
    ),
    url(
        r'^facultad/eliminar/(?P<pk>\d+)$',
        views.EliminarFacultad.as_view(),
        name='eliminar-facultad',
    ),
    url(
        r'^equipo/modificar/$',
        views.ActualizarEquipo.as_view(),
        name='modificar-equipo',
    ),
    url(
        r'^equipo/junta/secreatario$',
        views.ModificarSecretario.as_view(),
        name='modificar-secretario',
    ),
    url(
        r'^equipo/junta/tesorero$',
        views.ModificarTesorero.as_view(),
        name='modificar-tesorero',
    ),
    url(
        r'^comando/modificar/$',
        views.ActualizarComandoTecnico.as_view(),
        name='modificar-comando',
    ),
    url(
        r'^juntadirectiva/modificar/$',
        views.ActualizarJuntaDirectiva.as_view(),
        name='modificar-junta',
    ),
    url(
        r'^Pago/(?P<pk>\d+)$',
        views.RegistrarPago.as_view(),
        name='registrar-Pago'
    ),
    url(
        r'^Pago/listar/$',
        views.ListPago.as_view(),
        name='listar-Pago'
    ),
    url(
        r'^Pago/detalle/(?P<pk>\d+)$',
        views.detallePago.as_view(),
        name='detalle-Pago'
    ),
    url(
        r'^Pago/modificar/(?P<pk>\d+)$',
        views.ModificarPago.as_view(),
        name='modificar-Pago'
    ),
    url(
        r'^Pago/eliminar/(?P<pk>\d+)$',
        views.EliminarPago.as_view(),
        name='eliminar-Pago',
    ),
    url(
        r'^equipo/comando/tecnico$',
        views.ModificarTecnico.as_view(),
        name='modificar-tecnico',
    ),
    url(
        r'^equipo/comando/medico$',
        views.ModificarMedico.as_view(),
        name='modificar-medico',
    ),
    url(
        r'^equipo/comando/preparador$',
        views.ModificarPreparador.as_view(),
        name='modificar-preparador',
    ),
    url(
        r'^equipo/comando/delegado$',
        views.ModificarDelegado.as_view(),
        name='modificar-delegado',
    ),

    ##############################urls para frotend###############
    url(
        r'^equipo/listar/$',
        views.ListarEquipo.as_view(),
        name='listar-equipos'
    ),
]

apps/incidencias/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # url's de resultado
   url(
        r'^Resultados/$',
        views.RegistrarResultados.as_view(),
        name='registrar-Resultados'
    ),
    url(
        r'^Resultados/listar/$',
        views.ListResultados.as_view(),
        name='listar-Resultados'
    ),
    url(
        r'^Resultados/detalle/(?P<pk>\d+)$',
        views.detalleResultados.as_view(),
        name='detalle-Resultados'
    ),
    url(
        r'^Resultados/modificar/(?P<pk>\d+)$',
        views.ModificarResultados.as_view(),
        name='modificar-Resultados'
    ),
    url(
        r'^Resultados/eliminar/(?P<pk>\d+)$',
        views.EliminarResultados.as_view(),
        name='eliminar-Resultados',
    ),
    ###############################partido############################
    url(
        r'^Partido/$',
        views.RegistrarPartido.as_view(),
        name='registrar-Partido'
    ),
    url(
        r'^Partido/listar/$',
        views.ListPartido.as_view(),
        name='listar-Partido'
    ),
    url(
        r'^Partido/detalle/(?P<pk>\d+)$',
        views.detallePartido.as_view(),
        name='detalle-Partido'
    ),
    url(
        r'^Partido/modificar/(?P<pk>\d+)$',
        views.ModificarPartido.as_view(),
        name='modificar-Partido'
    ),
    url(
        r'^Partido/eliminar/(?P<pk>\d+)$',
        views.EliminarPartido.as_view(),
        name='eliminar-Partido',
    ),
    ###############################Incidencia############################
    url(
        r'^Incidencia/$',
        views.RegistrarIncidencia.as_view(),
        name='registrar-Incidencia'
    ),
    url(
        r'^Incidencia/listar/$',
        views.ListIncidencia.as_view(),
        name='listar-Incidencia'
    ),
    url(
        r'^Incidencia/detalle/(?P<pk>\d+)$',
        views.detalleIncidencia.as_view(),
        name='detalle-Incidencia'
    ),
    url(
        r'^Incidencia/modificar/(?P<pk>\d+)$',
        views.ModificarIncidencia.as_view(),
        name='modificar-Incidencia'
    ),
    url(
        r'^Incidencia/eliminar/(?P<pk>\d+)$',
        views.EliminarIncidencia.as_view(),
        name='eliminar-Incidencia',
    ),
    ##############################urls para frotend###############
    url(
        r'^Partidos/listar/$',
        views.ListarPartido.as_view(),
        name='listar-partidos'
    ),
    url(
        r'^Incidencias/listar/$',
        views.ListarIncidencias.as_view(),
        name='listar-incidencias'
    ),
    ##### urls inicencias ############
    url(
        r'^espectador/$',
        views.RegistrarEspectador.as_view(),
        name='registrar-espectador'
    ),
    url(
        r'^espectador/listar/$',
        views.ListEspectador.as_view(),
        name='listar-espectador'
    ),
    url(
        r'^espectador/detalle/(?P<pk>\d+)$',
        views.detalleEspectador.as_view(),
        name='detalle-espectador'
    ),
    url(
        r'^espectador/modificar/(?P<pk>\d+)$',
        views.ModificarEspectador.as_view(),
        name='modificar-espectador'
    ),
    url(
        r'^espectador/eliminar/(?P<pk>\d+)$',
        views.EliminarEspectador.as_view(),
        name='eliminar-espectador',
    )
]

apps/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(
        r'^$',
        views.HomeView.as_view(),
        name='home'
    ),
    url(
        r'^partidos/$',
        views.PartidoView.as_view(),
        name='partidos'
    ),
    url(
        r'^clasificacion/$',
        views.ClasificacionView.as_view(),
        name='clasificacion'
    ),
    url(
        r'^panel/$',
        views.InicioView.as_view(),
        name='inicio'
    ),
    url(
        r'^login/$',
        views.LogIn.as_view(),
        name='login'
    ),
    url(
        r'^usuario/salir/$',
        'apps.users.views.LogOut',
        name='logout'
    ),
    url(
        r'^add-admin/$',
        views.AgregarAdministrador.as_view(),
        name='agregar-administrador'
    ),
    url(
        r'^add-admin-equipo/$',
        views.AgregarAdmiEquipo.as_view(),
        name='administrador-equipo'
    ),
    url(
        r'^paneljunta/$',
        views.PanelJuntaDirectiva.as_view(),
        name='panel_juntadirectiva'
    )
    ,
    url(
        r'^ListAdmin/$',
        views.ListAdminEquipo.as_view(),
        name='Lista-Admin-Equipo'
    )
]

templates/panel/frotend/base_frontend.html
{% extends "base.html" %}

{% load  staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/materialize.css' %}">
    <link href='http://fonts.googleapis.com/css?family=Ubuntu:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

{% endblock css %}
{% block sidenav %}
<header>
  <nav class="cyan  grey darken-4">
  <div class="container">
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">Unsaac</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
      <ul class="right hide-on-med-and-down blue-text text-darken-2">
        <li><a href="{% url 'users_app:home' %}">Inicio</a></li>
        <li><a href="{% url 'incidencias_app:listar-partidos' %}">Partidos</a></li>
        <li><a href="{% url 'users_app:clasificacion' %}">Clasificacion</a></li>
        <li><a href="{% url 'equipo_app:listar-equipos' %}">Equipos</a></li>
        <li><a href="{% url 'incidencias_app:listar-incidencias' %}">Minuto a Minuto</a></li>
        <li><a href="{% url 'users_app:login' %}">Acceder</a></li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
       <li><a href="{% url 'users_app:home' %}">Inicio</a></li>
        <li><a href="{% url 'incidencias_app:listar-partidos' %}">Partidos</a></li>
        <li><a href="{% url 'users_app:clasificacion' %}">Clasificacion</a></li>
        <li><a href="{% url 'equipo_app:listar-equipos' %}">Equipos</a></li>
        <li><a href="{% url 'incidencias_app:listar-incidencias' %}">Minuto a Minuto</a></li>
        <li><a href="{% url 'users_app:login' %}">Acceder</a></li>
      </ul>
    </div>
  </div>
</nav>
</header>
    <main>
        {% block mensaje %}{% endblock mensaje %}
        {% block contenido_panel %}
        {% endblock contenido_panel %}

    </main>

{% endblock sidenav %}
{% block js %}
    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{% static 'js/materialize.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/init.js' %}"></script>
{% endblock js %}

templates/panel/frotend/clasificacion.html
{% extends "panel/frotend/base_frontend.html" %}
{% load staticfiles %}
{% block content %}
    <div class="card-panel grey lighten-4">
        <span>Equipos Participantes</span>

        <div class="row valign-wrapper">
            <div class="col m1">
                <img src="{% static 'img/psg.jpg' %}" alt="" class="circle responsive-img">
                <!-- notice the "circle" class -->
            </div>
            <div class="col m1">
                <img src="{% static 'img/bayer.png' %}" alt="" class="circle responsive-img">
                <!-- notice the "circle" class -->
            </div>
            <div class="col m1">
                <img src="{% static 'img/mu.jpg' %}" alt="" class="circle responsive-img">
                <!-- notice the "circle" class -->
            </div>
            <div class="col m1">
                <img src="{% static 'img/ars.png' %}" alt="" class="circle responsive-img">
                <!-- notice the "circle" class -->
            </div>
            <div class="col m1">
                <img src="{% static 'img/psg.jpg' %}" alt="" class="circle responsive-img">
                <!-- notice the "circle" class -->
            </div>
            <div class="col m1">
                <img src="{% static 'img/bar.png' %}" alt="" class="circle responsive-img">
                <!-- notice the "circle" class -->
            </div>
            <div class="col m1">
                <img src="{% static 'img/rm.jpg' %}" alt="" class="circle responsive-img">
                <!-- notice the "circle" class -->
            </div>
            <div class="col m1">
                <img src="{% static 'img/bayer.png' %}" alt="" class="circle responsive-img">
                <!-- notice the "circle" class -->
            </div>
            <div class="col m1">
                <img src="{% static 'img/mu.jpg' %}" alt="" class="circle responsive-img">
                <!-- notice the "circle" class -->
            </div>
            <div class="col m1">
                <img src="{% static 'img/rm.jpg' %}" alt="" class="circle responsive-img">
                <!-- notice the "circle" class -->
            </div>
            <div class="col m1">
                <img src="{% static 'img/bar.png' %}" alt="" class="circle responsive-img">
                <!-- notice the "circle" class -->
            </div>
            <div class="col m1">
                <img src="{% static 'img/ars.png' %}" alt="" class="circle responsive-img">
                <!-- notice the "circle" class -->
            </div>
            <div class="col m1">
                <img src="{% static 'img/rm.jpg' %}" alt="" class="circle responsive-img">
                <!-- notice the "circle" class -->
            </div>
            <div class="col m1">
                <img src="{% static 'img/bar.png' %}" alt="" class="circle responsive-img">
                <!-- notice the "circle" class -->
            </div>
        </div>
    </div>
    </div>
    <he class="flow-text">Tabla de Posiciones</h3>
        <table>
            <thead>
            <tr>
                <th data-field="id">Equipo</th>
                <th data-field="name">Carrera</th>
                <th>PG</th>
                <th>PE</th>
                <th>PP</th>
                <th>GF</th>
                <th>GC</th>
                <th>DG</th>
                <th data-field="price">PTS</th>
            </tr>
            </thead>

            {% for equipo in resultados %}
                <tbody>

                <tr>
                    <td>{{ equipo.equipo.nombre }}</td>
                    <td>{{ equipo.equipo.facultad }}</td>
                    <td>{{ equipo.gf }}</td>
                    <td>{{ equipo.gc }}</td>
                    <td>{{ equipo.pj }}</td>
                    <td>{{ equipo.pg }}</td>
                    <td>{{ equipo.pe }}</td>
                    <td>{{ equipo.pp }}</td>
                    <td>{{ equipo.ptos }}</td>
                </tr>
            {% endfor %}
            </tbody>
            <!--   <tbody>
               <tr>
                   <td>Sistemas</td>
                   <td>Eclair</td>
                   <td>$0.87</td>
                   <td>+12</td>
                   <td>+12</td>
                   <td>+12</td>
                   <td>+12</td>
                   <td>+12</td>
                   <td>+12</td>
               </tr>
               <tr>
                   <td>Sistemas</td>
                   <td>Eclair</td>
                   <td>$0.87</td>
                   <td>+12</td>
                   <td>+12</td>
                   <td>+12</td>
                   <td>+12</td>
                   <td>+12</td>
                   <td>+12</td>
               </tr>
               <tr>
                   <td>Sistemas</td>
                   <td>Eclair</td>
                   <td>$0.87</td>
                   <td>+12</td>
                   <td>+12</td>
                   <td>+12</td>
                   <td>+12</td>
                   <td>+12</td>
                   <td>+12</td>
               </tr>
               <tr>
                   <td>contabilidad</td>
                   <td>Eclair</td>
                   <td>$0.87</td>
                   <td>+12</td>
                   <td>+12</td>
                   <td>+12</td>
                   <td>+12</td>
                   <td>+12</td>
                   <td>+12</td>
               </tr>
               <tr>
                   <td>contabilidad</td>
                   <td>Eclair</td>
                   <td>$0.87</td>
                   <td>+12</td>
                   <td>+12</td>
                   <td>+12</td>
                   <td>+12</td>
                   <td>+12</td>
                   <td>+12</td>
               </tr>
               <tr>
                   <td>contabilidad</td>
                   <td>Eclair</td>
                   <td>$0.87</td>
                   <td>+12</td>
                   <td>+12</td>
                   <td>+12</td>
                   <td>+12</td>
                   <td>+12</td>
                   <td>+12</td>
               </tr>-->
            <!--   </tbody>-->
        </table>

        {% include "panel/footer.html" %}
{% endblock content %}

templates/panel/frotend/frontend.html
{% extends "panel/frotend/base_frontend.html" %}
{% load staticfiles %}
{% block content %}
        <div class="card-panel grey lighten-4">
          <span>Equipos Participantes</span>
          <div class="row valign-wrapper">
                <div class="col m1">
                  <img src="{% static 'img/psg.jpg' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
                </div>
                <div class="col m1">
                  <img src="{% static 'img/bayer.png' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
                </div>
                <div class="col m1">
                  <img src="{% static 'img/mu.jpg' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
                </div>
                <div class="col m1">
                  <img src="{% static 'img/ars.png' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
              </div>
                <div class="col m1">
                  <img src="{% static 'img/psg.jpg' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
                </div>
                <div class="col m1">
                  <img src="{% static 'img/bar.png' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
                </div>
                <div class="col m1">
                  <img src="{% static 'img/rm.jpg' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
                </div>
                <div class="col m1">
                  <img src="{% static 'img/bayer.png' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
                </div>
                <div class="col m1">
                  <img src="{% static 'img/mu.jpg' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
                </div>
                <div class="col m1">
                  <img src="{% static 'img/rm.jpg' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
                </div>
                <div class="col m1">
                  <img src="{% static 'img/bar.png' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
                </div>
                <div class="col m1">
                  <img src="{% static 'img/ars.png' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
                </div>
                <div class="col m1">
                  <img src="{% static 'img/rm.jpg' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
                </div>
                <div class="col m1">
                  <img src="{% static 'img/bar.png' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
                </div>
              </div>
          </div>
        </div>



  <div class="slider">
    <ul class="slides">            
      <li>
        <img src="{% static 'img/2.jpg' %}">
          <div class="caption right-align">
            <h3>Arsenal vs Juventus</h3>
            <h5>1-1</h5>
          </div>
      </li>
      <li>
        <img src="{% static 'img/3.jpg' %}">
          <div class="caption right-align">
            <h3>Real Madrid vs Barcelona</h3>                
            <h5>0-4</h5>
        </div>
      </li>
      <li>
        <img src="{% static 'img/2.jpg' %}">                
        <div class="caption right-align">
            <h3>Arsenal vs Olimpic</h3>
            <h7>3-0</h7>
        </div>
      </li>
    </ul>
  </div>

  <section>
    <h3>
      Siguientes encuentros
    </h3>
    <ul class="collection">
    <li class="collection-item avatar">
      <img src="{% static 'img/ars.png' %}" alt="" class="circle">
      <span class="title">ARS vs BAR</span>
      <p>Local: ARS<br>
         fecha: 12/12/2015  21:00 hs
      </p>
      <a href="#!" class="secondary-content"><i class="material-icons">ver mas</i></a>
    </li>
    <li class="collection-item avatar">
      <img src="{% static 'img/bayer.png' %}" alt="" class="circle">
      <span class="title">BM vs RM</span>
      <p>Local: BM<br>
         fecha: 12/12/2015  21:00 hs
      </p>
      <a href="#!" class="secondary-content"><i class="material-icons">ver mas</i></a>
    </li>
    <li class="collection-item avatar">
      <img src="{% static 'img/rm.jpg' %}" alt="" class="circle">
      <span class="title">ARS vs BAR</span>
      <p>Local: ARS<br>
         fecha: 12/12/2015  21:00 hs
      </p>
      <a href="#!" class="secondary-content"><i class="material-icons">ver mas</i></a>
    </li>
    <li class="collection-item avatar">
      <img src="{% static 'img/mu.jpg' %}" alt="" class="circle">
      <span class="title">ARS vs BAR</span>
      <p>Local: ARS<br>
         fecha: 12/12/2015  21:00 hs
      </p>
      <a href="#!" class="secondary-content"><i class="material-icons">ver mas</i></a>
    </li>
    <li class="collection-item avatar">
      <img src="{% static 'img/psg.jpg' %}" alt="" class="circle">
      <span class="title">ARS vs BAR</span>
      <p>Local: ARS<br>
         fecha: 12/12/2015  21:00 hs
      </p>
      <a href="#!" class="secondary-content"><i class="material-icons">ver mas</i></a>
    </li>
  </ul>
  </section>
  <script>
  $(document).ready(function(){
      $('.slider').slider();
    });
  </script>
{% include "panel/footer.html" %}
{% endblock content %}

templates/panel/frotend/partido.html
{% extends "panel/frotend/base_frontend.html" %}
{% load staticfiles %}
{% block content %}
        <div class="card-panel grey lighten-4">
          <span>Equipos Participantes</span>
          <div class="row valign-wrapper">
                <div class="col m1">
                  <img src="{% static 'img/psg.jpg' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
                </div>
                <div class="col m1">
                  <img src="{% static 'img/bayer.png' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
                </div>
                <div class="col m1">
                  <img src="{% static 'img/mu.jpg' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
                </div>
                <div class="col m1">
                  <img src="{% static 'img/ars.png' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
              </div>
                <div class="col m1">
                  <img src="{% static 'img/psg.jpg' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
                </div>
                <div class="col m1">
                  <img src="{% static 'img/bar.png' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
                </div>
                <div class="col m1">
                  <img src="{% static 'img/rm.jpg' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
                </div>
                <div class="col m1">
                  <img src="{% static 'img/bayer.png' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
                </div>
                <div class="col m1">
                  <img src="{% static 'img/mu.jpg' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
                </div>
                <div class="col m1">
                  <img src="{% static 'img/rm.jpg' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
                </div>
                <div class="col m1">
                  <img src="{% static 'img/bar.png' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
                </div>
                <div class="col m1">
                  <img src="{% static 'img/ars.png' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
                </div>
                <div class="col m1">
                  <img src="{% static 'img/rm.jpg' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
                </div>
                <div class="col m1">
                  <img src="{% static 'img/bar.png' %}" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
                </div>
              </div>
          </div>
        </div>
<p class="flow-text">Vea los Resultados de Todo Los Encuentros Jugados</p>
<div class="row">
    <div class="col s12 m4">
      <div class="card">
          <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="{% static 'img/2.jpg' %}">
          </div>
          <div class="card-content">
            <span class="card-title activator grey-text text-darken-4">BAR vs ARS<i class="material-icons right">...</i></span>
            <p class="blue-text">2-1</a></p>
          </div>
          <div class="card-reveal">
            <span class="card-title grey-text text-darken-4">BAR vs ARS<i class="material-icons right">close</i></span>
            <p class="blue-text">Detalles del Partido</a></p>
            <ul class="collection">
              <li class="collection-item avatar">
                <img src="{% static 'img/2.png' %}" alt="" class="circle">
                <span class="title">Nombre del Jugador</span>
                <p>Goles: 2 <br>
                  Acumulado: 5
                </p>
              </li>
              <li class="collection-item avatar">
                <img src="{% static 'img/bar.png' %}" alt="" class="circle">
                <span class="title">Nombre del Jugador</span>
                <p>Goles: 1 <br>
                  Acumulado: 1
                </p>
              </li>
            </ul>
          </div>
      </div>
    </div>
    <div class="col s12 m4">
      <div class="card">
          <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="{% static 'img/2.jpg' %}">
          </div>
          <div class="card-content">
            <span class="card-title activator grey-text text-darken-4">RM vs BM<i class="material-icons right">...</i></span>
            <p class="blue-text">2-1</a></p>
          </div>
          <div class="card-reveal">
            <span class="card-title grey-text text-darken-4">BAR vs ARS<i class="material-icons right">close</i></span>
            <p class="blue-text">Detalles del Partido</a></p>
            <ul class="collection">
              <li class="collection-item avatar">
                <img src="{% static 'img/bar.png' %}" alt="" class="circle">
                <span class="title">Nombre del Jugador</span>
                <p>Goles: 2 <br>
                  Acumulado: 5
                </p>
              </li>
              <li class="collection-item avatar">
                <img src="{% static 'img/bar.png' %}" alt="" class="circle">
                <span class="title">Nombre del Jugador</span>
                <p>Goles: 1 <br>
                  Acumulado: 1
                </p>
              </li>
            </ul>
          </div>
      </div>
    </div>
    <div class="col s12 m4">
      <div class="card">
          <div class="card-image waves-effect waves-block waves-light">
            <img class="activator" src="{% static 'img/3.jpg' %}">
          </div>
          <div class="card-content">
            <span class="card-title activator grey-text text-darken-4">PSG vs ARS<i class="material-icons right">...</i></span>
            <p class="blue-text">2-1</a></p>
          </div>
          <div class="card-reveal">
            <span class="card-title grey-text text-darken-4">BAR vs ARS<i class="material-icons right">close</i></span>
            <p class="blue-text">Detalles del Partido</a></p>
            <ul class="collection">
              <li class="collection-item avatar">
                <img src="{% static 'img/bar.png' %}" alt="" class="circle">
                <span class="title">Nombre del Jugador</span>
                <p>Goles: 2 <br>
                  Acumulado: 5
                </p>
              </li>
              <li class="collection-item avatar">
                <img src="{% static 'img/bar.png' %}" alt="" class="circle">
                <span class="title">Nombre del Jugador</span>
                <p>Goles: 1 <br>
                  Acumulado: 1
                </p>
              </li>
            </ul>
          </div>
      </div>
    </div>
</div>

{% include "panel/footer.html" %}
{% endblock content %}